spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: p4SSW0rd
    platform: mysql
    initialization-mode: NEVER
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: ALWAYS