version: '2.1'

services: 
  scan-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=demo
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
    volumes:
      - /opt/mysql_data:/var/lib/mysql
  ali-scan-scan:
    build: .
    depends_on:
      - scan-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=scan-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306